server:
  port: 8080

spring:
  application:
    name: PRODUCT-CATALOG-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: product-team
    password: product-team-pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: configserver:http://localhost:9296
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: product-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
